import { runArchitectureStageRunnerTests } from "./architecture/architecture-stage-runner.test.js";
import { runDesignDocumentBreakdownTests } from "./architecture/design-document-breakdown.test.js";
import { runCompositionRootTests } from "./app/composition-root.test.js";
import { runArtifactStoreTests } from "./shared/artifact-store.test.js";
import { runArchitectureDesignGeneratorTests } from "./architecture/architecture-design-generator.test.js";
import { runArchitectureDesignContractTests } from "./architecture/architecture-design-contract.test.js";
import { runChangeGateTests } from "./shared/change-gate.test.js";
import { runCliTests } from "./cli.test.js";
import { runImplementationContractTests } from "./implementation-execution/implementation-contract.test.js";
import { runImplementationPlanContractTests } from "./implementation-plan/implementation-plan-contract.test.js";
import { runImplementationPlanGeneratorTests } from "./implementation-plan/implementation-plan-generator.test.js";
import { runImplementationPlanStageRunnerTests } from "./implementation-plan/implementation-plan-stage-runner.test.js";
import { runImplementationGeneratorTests } from "./implementation-execution/implementation-generator.test.js";
import { runImplementationStageRunnerTests } from "./implementation-execution/implementation-stage-runner.test.js";
import { runHistoryStoreTests } from "./shared/history-store.test.js";
import { runLlmExecutorTests } from "./shared/llm-executor.test.js";
import { runModuleDesignContractTests } from "./module-design/module-design-contract.test.js";
import { runModuleDesignFanoutTests } from "./module-design/module-design-fanout.test.js";
import { runModuleDesignGeneratorTests } from "./module-design/module-design-generator.test.js";
import { runModuleDesignTemplateSpecTests } from "./module-design/module-design-template-spec.test.js";
import { runModuleStageRunnerTests } from "./module-design/module-stage-runner.test.js";
import { runOverallDesignContractRunnerTests } from "./overall-design-contract/overall-design-contract-runner.test.js";
import { runPipelineCoreTests } from "./workflow/pipeline-core.test.js";
import { runPipelineHandoffTests } from "./workflow/pipeline-handoff.test.js";
import { runPipelineStageEntryTests } from "./workflow/pipeline-stage-entry.test.js";
import { runRequirementContractTests } from "./requirement/requirement-contract.test.js";
import { runRequirementGeneratorTests } from "./requirement/requirement-generator.test.js";
import { runRequirementStageRunnerTests } from "./requirement/requirement-stage-runner.test.js";
import { runShellRunnerTests } from "./validation/shell-runner.test.js";
import { createTempDir } from "./workflow/pipeline-test-helpers.js";
import { runTraceTests } from "./shared/trace.test.js";
import { runWorkspaceLocalEnvTests } from "./shared/workspace-local-env.test.js";
import { runValidationModelTests } from "./validation/validation-model.test.js";
import { runValidationStageRunnerTests } from "./validation/validation-stage-runner.test.js";

async function main(): Promise<void> {
  const pipelineWorkspaceRoot = await createTempDir("pipeline-workspace-");
  await runArtifactStoreTests();
  await runArchitectureDesignGeneratorTests();
  await runArchitectureDesignContractTests();
  await runDesignDocumentBreakdownTests();
  await runArchitectureStageRunnerTests();
  await runCompositionRootTests();
  await runChangeGateTests();
  await runCliTests();
  await runHistoryStoreTests();
  await runImplementationContractTests();
  await runImplementationPlanContractTests();
  await runImplementationPlanGeneratorTests();
  await runImplementationPlanStageRunnerTests();
  await runImplementationGeneratorTests();
  await runImplementationStageRunnerTests();
  await runLlmExecutorTests();
  await runModuleDesignContractTests();
  await runModuleDesignFanoutTests();
  await runModuleDesignGeneratorTests();
  await runModuleDesignTemplateSpecTests();
  await runModuleStageRunnerTests();
  await runOverallDesignContractRunnerTests();
  await runPipelineCoreTests(pipelineWorkspaceRoot);
  await runPipelineStageEntryTests(pipelineWorkspaceRoot);
  await runPipelineHandoffTests(pipelineWorkspaceRoot);
  await runRequirementContractTests();
  await runRequirementGeneratorTests();
  await runRequirementStageRunnerTests();
  await runShellRunnerTests();
  await runTraceTests();
  await runWorkspaceLocalEnvTests();
  await runValidationModelTests();
  await runValidationStageRunnerTests();
  process.stdout.write("All tests passed.\n");
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.stack ?? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
